language: ruby
cache: bundler
matrix:
  fast_finish: true
rvm:
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - 2.6.0
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails5.gemfile
matrix:
  exclude:
    - rvm: 2.1.0
      gemfile: gemfiles/rails5.gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/rails5.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails3.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails4.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails3.gemfile
    - rvm: 2.6.0
      gemfile: gemfiles/rails3.gemfile
script: bundle exec rspec
before_install:
  - gem install bundler -v '< 2'